# 4.1 Data Wrangling and Advanced Indexing

**Goal:** Build data wrangling skills to clean and navigate datasets.

**Outline:**
* Numpy Array and DataFrame methods and functions
* Table indexing and slicing
* Boolean (logical) indexing
* Sorting
* Data cleaning and inspection

## Additional Required Reading: Functions
Data 8 textbook "Computational and Inferential Thinking: The Foundations of Data Science" By Ani Adhikari and John DeNero [Chapter 8 Functions and Tables](https://www.inferentialthinking.com/chapters/08/Functions_and_Tables.html). This should overlap with your assigned reading for Data 8.

## Numpy Arrays and DataFrames

NumPy and Pandas offer several types of data structures, the two main structures that we use are `nparray` and `DataFrame`. A `nparray` is a fast and flexible container for large datasets that allows you to perform operations on whole blocks of data at once. `nparray`s are best suited for homogenous (just one type) numerical data. `DataFrames` are designed for tabular datasets, and can handle heterogenous data (multiple types: int, float, string, etc.).


In [1]:
import numpy as np
import pandas as pd

### nparray

Here is an example of a `nparray` with random float data:

In [2]:
# Generate a random nparray called arr_data
arr_data = np.random.randn(5,3)
arr_data

array([[-0.0419345 , -1.16114793, -0.77874691],
       [ 1.53829581,  0.4330853 , -1.51268661],
       [-1.53649414,  0.65152418,  0.21474776],
       [ 0.01015001, -0.08328026,  0.33602064],
       [ 0.03194976, -1.35590311,  0.22993183]])

The function `arrayName.shape` is useful for finding the number of rows and columns in an array.

In [3]:
# use .shape to determine the shape of arr_data
arr_data.shape

(5, 3)

`arrayName.dtype` will display the data type of the data stored in the array.

In [4]:
# use .dtype to determine the type of arr_data
arr_data.dtype

dtype('float64')

The functions `np.zeros` and `np.ones` are similar, they create arrays full of zeros and ones respectively. The input for these functions is the shape of the array you want. This is an effective way of setting up an array of place-holders that you can then fill in with a loop or to make an array of a single value.

In [5]:
# Generate a nparray of zeros with np.zeros
arr0 = np.zeros((4,4))
arr0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Generate a nparray of ones with np.ones
arr1 = np.ones((4,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# np.ones is handy for making a nparray of any single value
arr5 = arr1 * 5
arr5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

The functions `np.arange` and `np.linspace` can be used to make monotonic number lines. They are really useful! `np.arange` makes an array of integers or floats between the starting and ending (note that the ending point is exclusive) in steps that you set as inputs. `np.linspace` will make evenly spaced float points between the starting and ending (note that the ending point is inclusive) you set.

In [8]:
# Generate an array of integers between 0 and 10 in steps of 1, including 0 (start) but not 11 (end)
arr2 = np.arange(0,11,1) 
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Generate an array of floats between 0 and 10 in steps of 2, including 0 (start) but not 11 (end)
arr2 = np.arange(0.0,11.0,2.0) 
arr2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [10]:
# Generate an array of 14 evenly spaced numbers between 0 and 10, including 0 (start) and 10 (end).
arr3=np.linspace(0,10,14) 
arr3

array([ 0.        ,  0.76923077,  1.53846154,  2.30769231,  3.07692308,
        3.84615385,  4.61538462,  5.38461538,  6.15384615,  6.92307692,
        7.69230769,  8.46153846,  9.23076923, 10.        ])

### DataFrames 

`Series` and `DataFrames` are like nparrays but they have the added feature of index labels assigned to each row and column -- the bold labels in the below `DataFrame`. These labels can be used to bin and select data.

In [11]:
# generate a new DataFrame
# note that index values (like the column labels) don't have to integers and don't have to be in order
frame = pd.DataFrame(np.random.rand(3, 3), index=['Nevada','Montana','Arizona'], columns=['sedimentary','igneous','metamorphic'])
frame

sedimentary   igneous  metamorphic
Nevada      0.724306  0.960806     0.156237
Montana     0.896371  0.932312     0.165291
Arizona     0.885512  0.797520     0.032702

We've seen `DataFrame` structures before in our tabular data files. The Earthquake catalog we were dealing with last week was a .csv (Comma Separated Variable) data file of all the earthquakes. We imported it as a DataFrame from the USGS API by setting up a query URL and using `pd.read_csv`. This time we'll look at the earthquakes of magnitude 2.5 and greater from the past week.

In [12]:
start_day = '2020-09-07'
end_day = '2020-09-14'
standard_url = 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=csv&orderby=magnitude'

query_url = standard_url + '&starttime=' + start_day + '&endtime=' + end_day + '&minmagnitude=2.5'
EQ_data = pd.read_csv(query_url)
EQ_data .head()

time  latitude  longitude   depth  mag magType  nst  \
0  2020-09-11T07:35:57.195Z  -21.3957   -69.9093   51.00  6.2     mww  NaN   
1  2020-09-12T02:44:10.969Z   38.7591   142.2473   32.09  6.1     mww  NaN   
2  2020-09-07T06:12:39.710Z  -17.1086   168.4935   10.00  6.0     mww  NaN   
3  2020-09-08T00:45:20.952Z   -4.9124   129.7627  174.05  5.9     mww  NaN   
4  2020-09-12T08:34:27.322Z  -17.2576   167.6786   10.00  5.9     mww  NaN   

    gap   dmin   rms  ...                   updated  \
0  72.0  0.076  0.87  ...  2020-09-25T10:13:28.654Z   
1  47.0  2.223  0.95  ...  2020-09-14T03:01:02.354Z   
2  41.0  2.065  1.13  ...  2020-10-04T13:09:52.650Z   
3  12.0  3.173  0.78  ...  2020-09-09T00:49:01.271Z   
4  64.0  1.857  0.70  ...  2020-09-25T12:11:10.835Z   

                             place        type horizontalError depthError  \
0    82 km NNE of Tocopilla, Chile  earthquake             6.3        1.9   
1       57 km SE of Ōfunato, Japan  earthquake             7.3        3.5   
2  72 km NNE of Port-Vila, Vanuatu  earthquake             6.9        1.8   
3  197 km SSE of Amahai, Indonesia  earthquake             6.4        3.6   
4                          Vanuatu  earthquake             6.0        1.9   

   magError  magNst    status  locationSource magSource  
0     0.071    19.0  reviewed              us        us  
1     0.057    30.0  reviewed              us        us  
2     0.098    10.0  reviewed              us        us  
3     0.086    13.0  reviewed              us        us  
4     0.043    51.0  reviewed              us        us  

[5 rows x 22 columns]

We have seen referencing individual columns (which are called `Series`) with: `DataFrame['Column_Name']`.

In [13]:
EQ_data['depth']

0       51.00
1       32.09
2       10.00
3      174.05
4       10.00
        ...  
416     25.60
417      6.90
418     21.00
419     10.30
420     94.50
Name: depth, Length: 421, dtype: float64

The `.values` function can be used to return the values of the `Series` as a `nparray`, so without the labled index values of the `Series`.

In [14]:
print(type(EQ_data['depth']))

<class 'pandas.core.series.Series'>


In [15]:
EQ_data['depth'].values

array([5.1000e+01, 3.2090e+01, 1.0000e+01, 1.7405e+02, 1.0000e+01,
       1.8000e+01, 1.0000e+01, 1.0000e+01, 5.5657e+02, 1.0000e+01,
       3.5000e+01, 6.1860e+01, 4.1170e+01, 3.1524e+02, 1.3872e+02,
       1.0000e+01, 1.3604e+02, 1.0000e+01, 1.0000e+01, 5.7700e+01,
       1.0000e+01, 9.8250e+01, 1.3161e+02, 1.0000e+01, 1.0000e+01,
       1.0000e+01, 1.3131e+02, 1.4900e+01, 1.0000e+01, 7.3140e+01,
       1.0000e+01, 4.1180e+01, 8.7260e+01, 3.5000e+01, 1.0000e+01,
       1.0000e+01, 1.0000e+01, 1.0000e+01, 1.0000e+01, 6.0190e+01,
       1.3834e+02, 1.3670e+01, 4.1180e+01, 2.4900e+01, 1.0000e+01,
       1.0370e+02, 1.0000e+01, 4.1160e+01, 4.6839e+02, 1.0000e+01,
       1.1292e+02, 1.3864e+02, 1.0000e+01, 1.0000e+01, 9.1600e+00,
       1.0000e+01, 1.0000e+01, 1.0000e+01, 6.7950e+01, 1.0000e+01,
       1.0000e+01, 8.4110e+01, 1.0000e+01, 1.0000e+01, 1.0000e+01,
       1.0000e+01, 1.0000e+01, 1.0000e+01, 1.0470e+01, 5.3357e+02,
       1.0000e+01, 7.7610e+01, 1.0000e+01, 1.0000e+01, 1.0000e

In [16]:
type(EQ_data['depth'].values)

numpy.ndarray

## Indexing and Slicing

Arrays and dataframes have two axes of indices, rows and columns. Remember that python indexing starts at zero, and the end bounds are generally exclusive.

![indices](./figures/indices.png)
> Source: Python for Data Analysis (2nd Edition) McKinney, W.

<br>

Using square brackes we can select subsections of tables to work with:

![slicing](./figures/array_slicing.png)
> Source: Python for Data Analysis (2nd Edition) McKinney, W.

In [17]:
# generate a random array
arr_data = np.random.randn(10,5)
arr_data

array([[ 0.09605226,  0.25417136,  0.43340318,  1.42651985,  2.48787137],
       [-0.43472232,  1.15376876, -0.3050159 ,  1.27640977, -1.24474966],
       [-0.27776326,  0.90278203,  0.13579767,  1.17787062, -0.54392391],
       [ 0.86133002,  1.06057301,  1.92276389,  0.16072731,  0.53197979],
       [-0.78815995,  1.87212373,  0.99579348, -1.90968352, -0.65583708],
       [ 1.02744067,  0.04324766,  1.49374235,  1.91576969,  0.08232494],
       [-1.3097444 ,  1.4499633 , -0.27065527, -0.10403068, -0.29193068],
       [ 0.20899699, -0.24895566,  0.85990728,  1.10714857,  1.8246234 ],
       [ 0.0049355 ,  1.14548161,  1.76695223,  0.23546711,  1.7680149 ],
       [-0.98147301,  0.6429534 , -0.74718615,  1.64055797,  0.85168331]])

**slice out the first 3 rows of arr_data**

In [18]:
a = arr_data[:3]
a

array([[ 0.09605226,  0.25417136,  0.43340318,  1.42651985,  2.48787137],
       [-0.43472232,  1.15376876, -0.3050159 ,  1.27640977, -1.24474966],
       [-0.27776326,  0.90278203,  0.13579767,  1.17787062, -0.54392391]])

**slice out the last 2 columns of arr_data**

In [19]:
b = arr_data[:,-2:]  
b

array([[ 1.42651985,  2.48787137],
       [ 1.27640977, -1.24474966],
       [ 1.17787062, -0.54392391],
       [ 0.16072731,  0.53197979],
       [-1.90968352, -0.65583708],
       [ 1.91576969,  0.08232494],
       [-0.10403068, -0.29193068],
       [ 1.10714857,  1.8246234 ],
       [ 0.23546711,  1.7680149 ],
       [ 1.64055797,  0.85168331]])

In [20]:
#Or this works too
b = arr_data[:,3:] 
b

array([[ 1.42651985,  2.48787137],
       [ 1.27640977, -1.24474966],
       [ 1.17787062, -0.54392391],
       [ 0.16072731,  0.53197979],
       [-1.90968352, -0.65583708],
       [ 1.91576969,  0.08232494],
       [-0.10403068, -0.29193068],
       [ 1.10714857,  1.8246234 ],
       [ 0.23546711,  1.7680149 ],
       [ 1.64055797,  0.85168331]])

Slicing a `DataFrame` is a bit different because you can reference the index labels and use `.iloc`.

**slice out the first 10 rows of EQ_data**

In [21]:
EQ_data.iloc[:10]

time  latitude  longitude   depth  mag magType  nst  \
0  2020-09-11T07:35:57.195Z  -21.3957   -69.9093   51.00  6.2     mww  NaN   
1  2020-09-12T02:44:10.969Z   38.7591   142.2473   32.09  6.1     mww  NaN   
2  2020-09-07T06:12:39.710Z  -17.1086   168.4935   10.00  6.0     mww  NaN   
3  2020-09-08T00:45:20.952Z   -4.9124   129.7627  174.05  5.9     mww  NaN   
4  2020-09-12T08:34:27.322Z  -17.2576   167.6786   10.00  5.9     mww  NaN   
5  2020-09-09T07:18:40.873Z    4.2064   126.6394   18.00  5.8     mww  NaN   
6  2020-09-07T06:29:14.938Z  -17.1622   168.5076   10.00  5.7     mww  NaN   
7  2020-09-07T17:40:44.171Z  -24.5120  -111.9898   10.00  5.6     mww  NaN   
8  2020-09-12T02:37:29.712Z  -17.8809  -178.0547  556.57  5.6     mww  NaN   
9  2020-09-08T08:28:51.109Z  -15.1768  -172.9244   10.00  5.4     mww  NaN   

     gap   dmin   rms  ...                   updated  \
0   72.0  0.076  0.87  ...  2020-09-25T10:13:28.654Z   
1   47.0  2.223  0.95  ...  2020-09-14T03:01:02.354Z   
2   41.0  2.065  1.13  ...  2020-10-04T13:09:52.650Z   
3   12.0  3.173  0.78  ...  2020-09-09T00:49:01.271Z   
4   64.0  1.857  0.70  ...  2020-09-25T12:11:10.835Z   
5   32.0  3.033  1.61  ...  2020-09-11T18:42:17.040Z   
6   41.0  2.116  0.83  ...  2020-10-04T09:05:11.136Z   
7   34.0  3.500  1.10  ...  2020-09-11T16:20:37.144Z   
8   36.0  3.553  1.10  ...  2020-09-13T02:41:07.273Z   
9  122.0  1.676  1.67  ...  2020-09-09T08:32:27.606Z   

                                 place        type horizontalError depthError  \
0        82 km NNE of Tocopilla, Chile  earthquake             6.3        1.9   
1           57 km SE of Ōfunato, Japan  earthquake             7.3        3.5   
2      72 km NNE of Port-Vila, Vanuatu  earthquake             6.9        1.8   
3      197 km SSE of Amahai, Indonesia  earthquake             6.4        3.6   
4                              Vanuatu  earthquake             6.0        1.9   
5  185 km SE of Sarangani, Philippines  earthquake             4.1        3.1   
6      66 km NNE of Port-Vila, Vanuatu  earthquake             7.0        1.8   
7                 Easter Island region  earthquake            10.2        1.8   
8             279 km E of Levuka, Fiji  earthquake             8.9        6.4   
9           127 km NE of Hihifo, Tonga  earthquake             9.9        2.0   

   magError  magNst    status  locationSource magSource  
0     0.071    19.0  reviewed              us        us  
1     0.057    30.0  reviewed              us        us  
2     0.098    10.0  reviewed              us        us  
3     0.086    13.0  reviewed              us        us  
4     0.043    51.0  reviewed              us        us  
5     0.053    34.0  reviewed              us        us  
6     0.050    38.0  reviewed              us        us  
7     0.066    22.0  reviewed              us        us  
8     0.089    12.0  reviewed              us        us  
9     0.098    10.0  reviewed              us        us  

[10 rows x 22 columns]

**slice out the a chunk of depths starting at index 5 and up to (but excluding) index 10**

In [22]:
EQ_data.iloc[5:10]['depth']

5     18.00
6     10.00
7     10.00
8    556.57
9     10.00
Name: depth, dtype: float64

Notice that this is still a `Series` with corresponding index values. If you just want the values from that chunk and not the index labels use `.values`.

In [23]:
EQ_data.iloc[5:10]['depth'].values

array([ 18.  ,  10.  ,  10.  , 556.57,  10.  ])

## Boolean Indexing

We can use Boolean (i.e. logical) indexing to select values from our DataFrame where the argument we want is `True`. You'll use the logical symbols (`<`,`>`,`==`,`&`,`|`,`~`).

**Use Boolean Indexing to filter out data so that we are only looking at rows with magnitudes larger than or equal to 6.0**

In [24]:
EQ_data[EQ_data['mag']>=6.0]

time  latitude  longitude  depth  mag magType  nst  \
0  2020-09-11T07:35:57.195Z  -21.3957   -69.9093  51.00  6.2     mww  NaN   
1  2020-09-12T02:44:10.969Z   38.7591   142.2473  32.09  6.1     mww  NaN   
2  2020-09-07T06:12:39.710Z  -17.1086   168.4935  10.00  6.0     mww  NaN   

    gap   dmin   rms  ...                   updated  \
0  72.0  0.076  0.87  ...  2020-09-25T10:13:28.654Z   
1  47.0  2.223  0.95  ...  2020-09-14T03:01:02.354Z   
2  41.0  2.065  1.13  ...  2020-10-04T13:09:52.650Z   

                             place        type horizontalError depthError  \
0    82 km NNE of Tocopilla, Chile  earthquake             6.3        1.9   
1       57 km SE of Ōfunato, Japan  earthquake             7.3        3.5   
2  72 km NNE of Port-Vila, Vanuatu  earthquake             6.9        1.8   

   magError  magNst    status  locationSource magSource  
0     0.071    19.0  reviewed              us        us  
1     0.057    30.0  reviewed              us        us  
2     0.098    10.0  reviewed              us        us  

[3 rows x 22 columns]

## Sorting

DataFrames can be sorted by the values in a given column (`.sort_values`).

In [25]:
EQ_data.sort_values(by=['depth']).head()

time   latitude   longitude  depth   mag magType  \
332  2020-09-10T12:09:31.800Z  44.322333 -110.520833   0.54  2.80      md   
370  2020-09-10T18:33:51.740Z  44.333333 -110.505500   1.19  2.62      ml   
397  2020-09-10T11:40:22.540Z  44.320333 -110.497000   1.20  2.56      ml   
334  2020-09-11T05:16:42.570Z  54.319300 -160.875200   1.40  2.80      ml   
252  2020-09-08T12:35:17.384Z  38.149700 -118.038300   1.80  3.50      ml   

      nst     gap     dmin     rms  ...                   updated  \
332  10.0  118.00  0.05854  0.2700  ...  2020-09-10T20:52:41.360Z   
370  17.0  125.00  0.07115  0.1800  ...  2020-09-10T19:12:59.040Z   
397  19.0  134.00  0.06052  0.2100  ...  2020-09-10T17:43:55.390Z   
334   NaN  209.00  0.90700  0.6000  ...  2020-09-25T07:35:41.040Z   
252  33.0   42.76  0.01500  0.1369  ...  2020-10-05T10:45:37.040Z   

                                     place        type horizontalError  \
332  59 km SE of West Yellowstone, Montana  earthquake            0.82   
370  60 km SE of West Yellowstone, Montana  earthquake            0.57   
397  61 km SE of West Yellowstone, Montana  earthquake            0.83   
334       115 km SSW of Sand Point, Alaska  earthquake            4.70   
252              27 km SSE of Mina, Nevada  earthquake             NaN   

    depthError  magError  magNst    status  locationSource magSource  
332       0.40     0.200     4.0  reviewed              uu        uu  
370       0.50     0.264     8.0  reviewed              uu        uu  
397       0.73     0.321     8.0  reviewed              uu        uu  
334       9.70     0.085    18.0  reviewed              us        us  
252       0.40     0.360    18.0  reviewed              nn        nn  

[5 rows x 22 columns]

You can reverse the order of sorting with `ascending=False`.

In [26]:
EQ_data.sort_values(by=['depth'],ascending=False).head()

time  latitude  longitude   depth  mag magType  nst  \
151  2020-09-07T22:22:20.306Z  -20.8541  -178.6937  605.20  4.3      mb  NaN   
217  2020-09-13T03:50:49.167Z  -21.8264  -179.4210  594.51  4.1      mb  NaN   
218  2020-09-13T04:05:15.875Z    6.0099   123.7340  556.61  4.1      mb  NaN   
8    2020-09-12T02:37:29.712Z  -17.8809  -178.0547  556.57  5.6     mww  NaN   
215  2020-09-11T04:25:44.348Z    5.9897   123.8273  539.45  4.1      mb  NaN   

       gap   dmin   rms  ...                   updated  \
151  115.0  4.359  0.82  ...  2020-09-14T04:12:05.040Z   
217  112.0  4.705  0.73  ...  2020-09-18T01:50:13.040Z   
218  146.0  5.276  0.60  ...  2020-09-18T01:56:50.040Z   
8     36.0  3.553  1.10  ...  2020-09-13T02:41:07.273Z   
215  107.0  5.720  0.41  ...  2020-09-16T23:11:57.040Z   

                                   place        type horizontalError  \
151                          Fiji region  earthquake            14.9   
217                          Fiji region  earthquake            12.9   
218  54 km WSW of Palimbang, Philippines  earthquake            11.3   
8               279 km E of Levuka, Fiji  earthquake             8.9   
215  46 km WSW of Palimbang, Philippines  earthquake            11.5   

    depthError  magError  magNst    status  locationSource magSource  
151        8.6     0.116    21.0  reviewed              us        us  
217        8.5     0.115    21.0  reviewed              us        us  
218       15.2     0.198     7.0  reviewed              us        us  
8          6.4     0.089    12.0  reviewed              us        us  
215       11.9     0.126    17.0  reviewed              us        us  

[5 rows x 22 columns]

## Data cleaning and inspection

`.drop()` can be used to drop whole columns from a DataFrame.

In [27]:
EQ_data_concise = EQ_data.drop(['magType','nst','gap','dmin','rms','net','id','updated','place','type','horizontalError','depthError','magError','magNst','status','locationSource','magSource',], axis='columns')
EQ_data_concise.head()

time  latitude  longitude   depth  mag
0  2020-09-11T07:35:57.195Z  -21.3957   -69.9093   51.00  6.2
1  2020-09-12T02:44:10.969Z   38.7591   142.2473   32.09  6.1
2  2020-09-07T06:12:39.710Z  -17.1086   168.4935   10.00  6.0
3  2020-09-08T00:45:20.952Z   -4.9124   129.7627  174.05  5.9
4  2020-09-12T08:34:27.322Z  -17.2576   167.6786   10.00  5.9

`.unique()` returns the unique values from the specified object.

In [28]:
unique_mags = EQ_data_concise['mag'].unique()
unique_mags.sort()
unique_mags

array([2.5 , 2.51, 2.53, 2.54, 2.55, 2.56, 2.57, 2.58, 2.6 , 2.61, 2.62,
       2.63, 2.64, 2.65, 2.66, 2.68, 2.69, 2.7 , 2.74, 2.75, 2.76, 2.77,
       2.78, 2.79, 2.8 , 2.81, 2.82, 2.84, 2.86, 2.87, 2.9 , 2.91, 2.92,
       2.95, 2.96, 2.97, 2.98, 2.99, 3.  , 3.01, 3.02, 3.03, 3.06, 3.1 ,
       3.17, 3.18, 3.2 , 3.21, 3.23, 3.26, 3.3 , 3.32, 3.34, 3.42, 3.43,
       3.44, 3.46, 3.5 , 3.53, 3.59, 3.6 , 3.7 , 3.71, 3.72, 3.74, 3.75,
       3.83, 3.9 , 4.  , 4.1 , 4.2 , 4.22, 4.3 , 4.33, 4.36, 4.4 , 4.5 ,
       4.6 , 4.7 , 4.8 , 4.9 , 5.  , 5.1 , 5.2 , 5.3 , 5.4 , 5.6 , 5.7 ,
       5.8 , 5.9 , 6.  , 6.1 , 6.2 ])

`.value_counts()` returns the count of each unique value from the specified object. This functionality can be used to find duplicate values.

In [29]:
EQ_data_concise['mag'].value_counts()

4.40    31
4.30    30
4.60    26
4.20    26
4.50    26
        ..
2.77     1
6.20     1
5.80     1
4.33     1
6.00     1
Name: mag, Length: 93, dtype: int64

### Finding missing data (NaNs)

NaN stands for not a number and is used as a placeholder in data tables where no value exists. `np.isnan` returns a boolean object with True where NaNs appear in the DataFrame.

In [30]:
np.isnan(EQ_data['nst'])

0       True
1       True
2       True
3       True
4       True
       ...  
416     True
417    False
418     True
419     True
420     True
Name: nst, Length: 421, dtype: bool

In [31]:
~np.isnan(EQ_data['nst'])

0      False
1      False
2      False
3      False
4      False
       ...  
416    False
417     True
418    False
419    False
420    False
Name: nst, Length: 421, dtype: bool

You can use this boolean object to filter-out rows that contain NaNs.

In [32]:
EQ_data[~np.isnan(EQ_data['nst'])]

time   latitude   longitude  depth   mag magType  \
145  2020-09-12T23:22:04.540Z  19.304600  -64.389600  40.00  4.36      md   
146  2020-09-13T07:12:58.980Z  19.396000  -64.284100  35.00  4.33      md   
177  2020-09-11T07:55:45.450Z  36.440667 -117.994500   3.93  4.22      ml   
234  2020-09-08T01:19:54.510Z  19.121300  -64.398500  38.00  3.83      md   
235  2020-09-08T06:35:40.270Z  19.316600  -64.570800  37.00  3.83      md   
..                        ...        ...         ...    ...   ...     ...   
403  2020-09-08T11:03:53.600Z  18.027300  -66.828000  16.00  2.51      md   
404  2020-09-13T17:55:42.130Z  19.182333 -155.475833  32.80  2.51      md   
405  2020-09-07T08:24:04.300Z  17.932000  -66.947100  13.00  2.50      md   
415  2020-09-11T12:23:38.700Z  44.315167 -110.494500   1.87  2.50      ml   
417  2020-09-12T05:56:08.720Z  38.169800 -117.964800   6.90  2.50      ml   

      nst    gap     dmin     rms  ...                   updated  \
145  19.0  233.0  1.86560  0.4800  ...  2020-09-25T03:01:38.040Z   
146  26.0  234.0  2.00520  0.2900  ...  2020-09-13T15:15:36.449Z   
177  45.0   66.0  0.06908  0.1800  ...  2020-09-25T10:09:14.879Z   
234  17.0  338.0  1.74990  0.4000  ...  2020-09-09T00:54:19.040Z   
235  20.0  335.0  1.73570  0.4100  ...  2020-09-08T08:09:44.040Z   
..    ...    ...      ...     ...  ...                       ...   
403  12.0  117.0  0.07310  0.1500  ...  2020-09-08T11:14:28.314Z   
404  59.0   82.0      NaN  0.1200  ...  2020-09-14T23:42:34.030Z   
405  16.0  221.0  0.08040  0.1300  ...  2020-09-07T09:46:21.114Z   
415  15.0  144.0  0.05648  0.1800  ...  2020-09-11T14:39:34.760Z   
417  28.0   47.8  0.03100  0.1599  ...  2020-09-25T11:03:38.040Z   

                                           place        type horizontalError  \
145  115 km NNE of Cruz Bay, U.S. Virgin Islands  earthquake            3.57   
146  129 km NNE of Cruz Bay, U.S. Virgin Islands  earthquake            1.81   
177                    18km SSE of Lone Pine, CA  earthquake            0.18   
234   96 km NNE of Cruz Bay, U.S. Virgin Islands  earthquake            3.23   
235  111 km NNE of Cruz Bay, U.S. Virgin Islands  earthquake            3.32   
..                                           ...         ...             ...   
403               2 km ESE of Yauco, Puerto Rico  earthquake            0.58   
404                     2 km S of Pāhala, Hawaii  earthquake            0.44   
405              6 km SW of Guánica, Puerto Rico  earthquake            0.79   
415        61 km SE of West Yellowstone, Montana  earthquake            0.50   
417                    27 km SSE of Mina, Nevada  earthquake             NaN   

    depthError  magError  magNst    status  locationSource magSource  
145      29.63  0.060000     8.0  reviewed              pr        pr  
146      21.72  0.130000    16.0  reviewed              pr        pr  
177       0.57  0.140000   320.0  reviewed              ci        ci  
234      24.52  0.110000    14.0  reviewed              pr        pr  
235      26.87  0.120000    10.0  reviewed              pr        pr  
..         ...       ...     ...       ...             ...       ...  
403       0.73  0.150000     5.0  reviewed              pr        pr  
404       0.60  0.152709    27.0  reviewed              hv        hv  
405       0.30  0.120000    11.0  reviewed              pr        pr  
415       2.06  0.377000     8.0  reviewed              uu        uu  
417       0.60  0.290000    15.0  reviewed              nn        nn  

[105 rows x 22 columns]

## Further Reading (Optional)

This user guide has lots of useful examples and documentation:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html